name: type_language
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0-365.0.dev

# Add regular dependencies here.
dependencies:
  # crc32:
  petitparser: ^5.3.0
  # path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
  zekfad_lints:

dependency_overrides:
  # crc32:
  #   git: https://github.com/LacticWhale/CRC32.git
  zekfad_lints:
    git: https://github.com/Zekfad/dart_lints.git
