name: type_language
description: A starting point for Dart libraries or applications.
version: 1.0.1
repository: https://github.com/LacticWhale/type_language

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  petitparser: ^6.1.0

dev_dependencies:
  test: ^1.21.0
  zekfad_lints:

dependency_overrides:
  zekfad_lints:
    git: https://github.com/Zekfad/dart_lints.git
